### ISSUE TITLE
20 small swarms

### ISSUE THREAD

**Issue by Floor97** [ChrisSBras/trustchain-superapp#1]
- [x] Find 20 videos ([creative commons license](https://www.google.com/search?q=creative+commons)).
- [x] Create torrent for each video
- [x] Be able to download the torrent in detoks

Resources:
[IPv8 community for content discovery and magnet link downloading](https://github.com/Tribler/trustchain-superapp/blob/master/musicdao/src/main/java/nl/tudelft/trustchain/musicdao/core/torrent/TorrentEngine.kt#L99)
[IPv8 community gossip-code](https://github.com/Tribler/trustchain-superapp/blob/master/musicdao/src/main/java/nl/tudelft/trustchain/musicdao/core/ipv8/ReleaseBlockGossiper.kt#L29)

**Comment by ChelseaGuan** [comment]
Initially, I tried to use the `download` function from TorrentEngine in `trustchain.musicdao`. However, there were issues with complex dependencies, so I tried implementing a simpler version of the download function in `trustchain.detoks`. 
Right now, I have a problem with sessionManager.fetchMagnet(magnet, 10), since it always returns null, so the program cannot continue.

**Comment by ChelseaGuan** [comment]
By manually uploading the Creative Commons videos to archive.org and using the torrent file it generates, we are now able to download the videos from the torrent in detoks. It is likely because archive.org provides better trackers and actually has seeders for the torrents. Furthermore, it downloading torrents works with the gossiper.

**Comment by Floor97** [comment]
The torrent files were not downloading is because the original torrent files only contained one video at a time. Since this was not enough for the cache size it didn't start the downloading of the videos ([code](https://github.com/ChrisSBras/trustchain-superapp/blob/master/detoks/src/main/java/nl/tudelft/trustchain/detoks/TorrentManager.kt#L119)). Since it is beneficial to be able to boot peers with multiple torrents I have been looking into being able to grab all files wth a `.torrent` extension from raw instead of just the default. However, this involves reflection, and currently am still debugging as it is not printing any errors.

**Comment by Floor97** [comment]
Since the dummy nodes can select torrents dynamically from a list, the `detoks.torrent` will remain the only hardcoded torrent on boot of the superapp. Instead to test the network the 20 torrents will be added to the torrents folder for the dummy nodes only.
