### ISSUE TITLE
Token transaction

### ISSUE THREAD

**Issue by Floor97** [ChrisSBras/trustchain-superapp#3]
When a video is downloaded from a peer, a token transaction occurs.

Phone-to-Phone overlay and tokens. transaction format [[example trustchain docs](https://github.com/Tribler/kotlin-ipv8/blob/master/doc/TrustChainCommunity.md)], sign with private key, and transfer to another phone using overlay. [Python IPv8 overlay examples and tutorial](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.html)

**Comment by AlexDumitru17** [comment]
Implement half block transactions, use a skeleton (simple) wallet to store the tokens.

**Comment by AlexDumitru17** [comment]
For now, a basic implementation of a wallet can be found in the DetoksCommunity on branch token-transaction-trustchain. So far, it only follows the ipv8 protocol, so no trustchain implementation. In order to implement a trustchain community, an SQLite database should be set up to store transaction history & such. I had some problems setting it up but I found some examples from other projects which seem helpful.
